### ISSUE TITLE
Add config files supporting older versions of docker compose

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/recipes#11]
We've encountered a few times now that some institutional servers have (and are likely constrained to) a docker compose version that's a major version below what we are using (i.e., v1.1x.x).

This older (deprecated) compose version both requires different syntax for commands (`docker-compose` instead of `docker compose`) and lacks some of the features that compose v2 supports. This means the docker-compose.yml file and other commands need to be adjusted on these systems to be able to successfully deploy a Neurobagel node stack.

**Comment by alyssadai** [comment]
When you have a chance @surchs, could you add the notes from our debugging meeting with Eric today under `Changes that need to be made for docker compose v1`?

**Comment by surchs** [comment]
Thanks for the ping @alyssadai. My notes were:

For older versions of docker compose (in this case `v1.17.1`):

- inline comments in `.env` files are not ignored (e.g. `NB_PORT = 8000 # some comment` will not work correctly)
- `docker-compose config` on these older versions does not seem to create (by default) a dedicated docker network for all the services, which is a problem because we rely on the services being able to discover each other by their names

**Comment by alyssadai** [comment]
@neurobagel/dev should we close this issue as not planned for now?

Based on our current docs and our support experiences, my sense is that we don't plan to support older Docker Compose / Docker versions.
