### ISSUE TITLE
Non-robust default value for `NB_API_QUERY_URL` in Compose recipes

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/recipes#21]
As (re-)discovered in https://github.com/neurobagel/planning/issues/111#issuecomment-1955461496, when the query tool is part of a deployment that is meant to be accessed from *other* machines, the URL used for the API that it talks to has to be provided as it would appear to an external user on their *own* machine.

The query tool essentially always behaves as if the user has downloaded it and then run it on their own machine. So, `NB_API_QUERY_URL` must be set to a URL that makes sense from outside the machine hosting the API, such as the public IP of the host, or the subdomain for the API if NGINX is set up on the machine.

One exception is if a user tries deploying our API stack on their local machine (and then tries the query tool from the same machine), in which case `NB_API_QUERY_URL` would need to be `localhost` (also because their laptop would not have a unique public IP). This should be documented clearly in a note to the user.

Meanwhile, we should update the default in the `.env` file to a clearly toy/must-be-changed URL, e.g.:
- 12.34.56.78
- XX.XX.XX.XX

- See also https://github.com/neurobagel/query-tool/pull/343

**Comment by surchs** [comment]
Starting the spec here: @neurobagel/dev between these two options:

> 12.34.56.78
XX.XX.XX.XX

I prefer the `XXX` one because it is clearly a placeholder, whereas the `12.34.etc` one requires an extra glance to understand as a placeholder. With an extra comment to explain: **please change this** and use `localhost` if run only locally, I think this should be fine. 

Once we get to #30, we could make this even more visible by putting the `NB_API_QUERY_URL` in the section of ENV variables **to pay attention to**, i.e. at the top of the file.

**Comment by alyssadai** [comment]
I think the `XXX` option is fine!
